### ISSUE TITLE
strftime: garbage from %z, garbage and segfaults from %Z

### ISSUE THREAD

**Issue by RhodiumToad** [luaposix/luaposix#336]
This is the same underlying problem as issue #321 but without the distraction of leapseconds which confused the original report.

Because none of the PosixTm functions make any attempt to preserve `tm_gmtoff` and `tm_zone`, then on platforms which use those extra members of `struct tm`, any use of `%z` in `strftime` produces garbage due to reading an uninitialized value, and any use of `%Z` has the potential to crash due to accessing an uninitialized pointer.

Making reproducible test cases is hard because the uninitialized data is on the stack and therefore the result may be compiler dependent. However it is easy to observe that the result of `strftime("%z", localtime())` is correct only by coincidence (e.g. on my system it is almost always `+0000` regardless of timezone) and that `%Z` can produce garbage or segfaults.

**Comment by gvvaughan** [comment]
Thanks for the report and the diagnosis.

Actually a reproducible failure is less important than a reproducible success case that proves everything is fixed correctly.

Are you interested in working on a patch?

**Comment by RhodiumToad** [comment]
Actually fixing the problem is relatively straightforward (though I ran into some other bugs along the way, like the fact that `optstringfield` doesn't work at all (fortunately, nothing uses that) and `checkstringfield` uses lua_tolstring unsafely).

The hard part is the question of maintaining build compatibility with platforms that don't have tm_gmtoff or tm_zone; I don't know if there is any existing way to make `luke` check for that.

**Comment by gvvaughan** [comment]
Please file separate issues for any new bugs you find, so I don’t lose track - luaposix is a fairly large project for one person to maintain, so I do rely on issues raised and am always delighted with pull requests.

I wrote luke to provide autoconf-like machinery without requiring m4 and Perl and then generating a 500k shell script to carry around. I’d be happy to help add a means to test for struct members and pass a cpp define at compile time based on the result if that’s the only thing holding you back from a patch for this issue?

**Comment by RhodiumToad** [comment]
Yes, a way to get a cpp define for the presence of a struct member would be enough.

**Comment by gvvaughan** [comment]
Done!

If you pull the latest `build-aux/luke` (version 0.2.2) from https://github.com/gvvaughan/luke into `luaposix/build-aux/luke`, you can then change the relevant section of `lukefile` to something like:

```lua
   ['posix.time']      = {
      defines   = {
         HAVE_TM_TM_GMTOFF = {checkmember='struct tm.tm_gmtoff', include='time.h'},
         HAVE_TM_TM_TZONE   = ...
      },
     ...
   },
```

And then patch `ext/posix/time.c` as necessary.
...in the lukefile for

**Comment by RhodiumToad** [comment]
First attempt isn't working on linux because apparently different CFLAGS are being used when testing for the members in luke, as compared to doing the actual compile; specifically, defining _POSIX_C_SOURCE or _XOPEN_SOURCE looks like it's turning off __USE_MISC, which changes the names of the struct members (which is insane, but I have never regarded linux as sane).

Is there any reason not to add _DEFAULT_SOURCE to the defines when building for linux?

**Comment by gvvaughan** [comment]
I’m afraid of changing those defines... it took a lot of trial and error to reach a selection that exposes all the right POSIX2008 APIs that we rely on.

It sounds like a bug in Luke to me. I’ll take a look at whether it makes sense to try and propagate the default flags at configure time.

In the mean time, if you add `_DEFAULT_SOURCE` to the Linux platform flags in lukefile, does everything still build and pass the test suite on your Linux?

**Comment by RhodiumToad** [comment]
I don't have a linux to test on (I never use it). I only got the error from the CI build of the pull request. I will try that again with `_DEFAULT_SOURCE` to see what happens.

Fixing it in luke without setting `_DEFAULT_SOURCE` doesn't solve the underlying problem, since then luke will just say that tm_gmtoff and tm_zone don't exist, and we're back to crashing.

**Comment by RhodiumToad** [comment]
Well that obviously didn't work, it looks like some `require()` is now failing, but the CI output does not indicate what.

**Comment by RhodiumToad** [comment]
OK, that turned out to be my fault, a stray reference to lua53 rather than lua in luke.

Build with _DEFAULT_SOURCE is now passing tests on Travis-CI.
